name: Docker2
channels:
  - conda-forge
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.11.12
  - icu=75.1
  - libblas=3.11.0
  - libcblas=3.11.0
  - libcxx=21.1.6
  - libexpat=2.7.3
  - libffi=3.5.2
  - libgcc=15.2.0
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - liblapack=3.11.0
  - liblzma=5.8.1
  - libopenblas=0.3.30
  - libsqlite=3.51.0
  - libzlib=1.3.1
  - llvm-openmp=21.1.6
  - ncurses=6.5
  - numpy=1.26.4
  - openssl=3.6.0
  - pandas=2.1.4
  - pip=25.3
  - python=3.11.14
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.2
  - python_abi=3.11
  - pytz=2025.2
  - readline=8.2
  - setuptools=80.9.0
  - six=1.17.0
  - tk=8.6.13
  - tzdata=2025b
  - wheel=0.45.1
prefix: /Users/zainnofal/miniforge3/envs/Docker2
